CREATE TABLE t11(`name` CHAR(4));

INSERT INTO t11 VALUES('abcd');
INSERT INTO t11 VALUES('欢迎光临');

INSERT INTO t11 VALUES('ab北京');
SELECT*FROM t11;

CREATE TABLE t13(content TEXT,content2 MEDIUMTEXT,content3 LONGTEXT);
INSERT INTO t13 VALUES('你好','我是汪洋', '这里汪洋1000000');
SELECT*FROM t13;