INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (4, 'shenjiayan', 83, 72, 91);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (1, 'wangyang', 89, 78, 90);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (2, 'wangmiduo', 79, 68, 80);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (5, 'chengshenheng', 81, 76, 70);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (7, 'aoki', 84, 65, 70);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (3, 'shenjiayan', 69, 88, 50);
INSERT INTO `orderby` (`id`, `name`, `chinese`, `english`, `math`) VALUES (6, 'tanaka', 33, 22, 44);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('wangyang', 257);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('shenjiayan', 246);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('wangmiduo', 227);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('chengshenheng', 227);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('aoki', 219);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('shenjiayan', 207);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('tanaka', 99);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('wangyang', 257);
INSERT INTO `orderby` (`name`, `total_score`) VALUES ('wangmiduo', 227);
